version: '2'
services:
    redis:
        image: redis
        ports:
            - "6379:6379"
        restart: always
    web:
        image: kuzditomi-signalrpoc-hubservice
        build: ./SignalrScalingPoc.PushService
        expose: 
            - "80"
        depends_on: [ redis ]
    lb:
        image: 'haproxy'
        links:
            - web
        ports:
            - "9911:8080"
        volumes:
        - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"